--- SKSE plugin rule for FreeClimb.
---
--- CommonLibNG ships `commonlibsse-ng.plugin`, but that rule can only emit
--- `AddressLibrary` / `SignatureScanning` runtime compatibility. FreeClimb pins an
--- explicit list of runtimes (same as `COMPATIBLE_RUNTIMES` in CMakeLists.txt), so
--- this rule reuses the shared `commonlib.plugin` base (rc file, install, package)
--- and generates its own `SKSEPluginInfo`.
---
--- # Options
--- - `name`        : Plugin name. Default: target name.
--- - `author`      : Author shown in the rc file and plugin info.
--- - `description` : Description shown in the rc file.
--- - `runtimes`    : Compatible runtime versions, e.g. `{ "1.5.97.0", "1.6.1170.0" }`.
---
--- # Example
--- ```lua
--- add_rules("freeclimb.plugin", { author = "Epsilona", runtimes = RUNTIMES })
--- ```
rule("freeclimb.plugin", function ()
    add_deps("commonlib.plugin")

    on_load(function (target)
        local conf = target:extraconf("rules", "freeclimb.plugin") or {}

        -- Read by `commonlib.plugin` to fill the rc file.
        target:data_set("commonlib.plugin.config", conf)
        target:data_set("commonlib.plugin.package", { prefixdir = "Data" })
    end)

    on_config(function (target)
        local conf = target:extraconf("rules", "freeclimb.plugin") or {}

        --- Convert `"1.6.1170"` into `REL::Version{ 1, 6, 1170, 0 }`.
        local function literal(text)
            local parts = (text or "0"):split("%.")
            while #parts < 4 do
                table.insert(parts, "0")
            end
            return format("REL::Version{ %s }", table.concat(parts, ", ", 1, 4))
        end

        -- Runtime list: explicit versions, or Address Library when empty.
        local runtimes = conf.runtimes or {}
        assert(#runtimes <= 16, "SKSE accepts at most 16 compatible runtimes")

        local compat = "SKSE::VersionIndependence::AddressLibrary"
        if #runtimes > 0 then
            local items = {}
            for _, version in ipairs(runtimes) do
                table.insert(items, literal(version))
            end
            compat = "{ " .. table.concat(items, ", ") .. " }"
        end

        -- Same layout as the file generated by `add_commonlibsse_plugin` in CMake.
        local lines = {
            "#include \"REL/Relocation.h\"",
            "#include \"SKSE/SKSE.h\"",
            "",
            "SKSEPluginInfo(",
            format("    .Version = %s,", literal(target:version())),
            format("    .Name = \"%s\"sv,", conf.name or target:name()),
            format("    .Author = \"%s\"sv,", conf.author or ""),
            format("    .SupportEmail = \"%s\"sv,", conf.contact or ""),
            "    .StructCompatibility = SKSE::StructCompatibility::Independent,",
            format("    .RuntimeCompatibility = %s,", compat),
            "    .MinimumSKSEVersion = REL::Version{ 0, 0, 0, 0 }",
            ")",
            "",
        }
        local content = table.concat(lines, "\n")

        -- Rewrite only when changed, so incremental builds stay incremental.
        local file = path.join(target:autogendir(), "PluginInfo.cpp")
        if not os.isfile(file) or io.readfile(file) ~= content then
            io.writefile(file, content)
        end

        target:add("deps", "commonlibsse-ng")
        target:add("files", file)

        -- `xmake install` target. Env vars win, then `$(builddir)/install`.
        local mods = os.getenv("XSE_TES5_MODS_PATH")
        local game = os.getenv("XSE_TES5_GAME_PATH")
        if mods then
            target:set("installdir", path.join(mods, target:name()))
        elseif game then
            target:set("installdir", path.join(game, "Data"))
        elseif not target:get("installdir") then
            target:set("installdir", path.join(os.projectdir(), "build", "install"))
        end

        target:add("installfiles", target:targetfile(), { prefixdir = "SKSE/Plugins" })
        target:add("installfiles", target:symbolfile(), { prefixdir = "SKSE/Plugins" })
    end)
end)
